# Generated by Django 5.2.5 on 2025-08-21 04:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=100)),
                ('transmission', models.CharField(choices=[('manual', 'Mecánico'), ('automatic', 'Automático'), ('electric', 'Eléctrico')], max_length=10)),
                ('mileage', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='cars/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_sold', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('combustion', 'Combustión'), ('electric', 'Eléctrico'), ('automatic', 'Automática'), ('semi_automatic', 'Semiautomática')], max_length=15)),
                ('mileage', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='motorcycles/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_sold', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
