# Generated by Django 5.2.5 on 2025-08-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_discount_featureditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureditem',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='featureditem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='featureditem',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
