# Generated by Django 5.2.5 on 2025-08-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_featureditem_image_url_featureditem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='discount',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
